apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
      spec:
        containers:
          - name: banking-app
            image: 471112749395.dkr.ecr.us-east-1.amazonaws.com/banking-app:latest
            imagePullPolicy: Always
            command: ["java", "-jar", "BankApp.jar"]
            ports:
              - containerPort: 8080